### ISSUE TITLE
"VK_DBG_LAYER_DEBUG_OUTPUT" used instead of "VK_DBG_LAYER_ACTION_DEBUG_OUTPUT"

### ISSUE THREAD

**Issue by jzulauf-lunarg** [LunarG/VulkanTools#1071]
In the json for the debug actions an invalid action string is specified, causing DebugOutput action to fail to operate as anticipated.

**Comment by richard-lunarg** [comment]
This is being addressed in PR #1070.

**Comment by richard-lunarg** [comment]
The vkconfig in  current SDK silently supresses all validation messages when the "Debug Output" option is selected.  User surveys have shown that most of our users use layers in conjunction with the debugger.  However most of those users already have their own validation hooks and enable features programatically instead of through vkconfig.

Affect users are those that attempt to use vkconfig to set up layers for debugging  applications without their own validation hooks
