### ISSUE TITLE
vkconfig: Ensure new devsim layer is supported with adequate layer ordering

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1160]
The Select Layers dialog has lost the ability to order layer precedence. While the override layers do not have "complete" control over the layers an application loads, it does control those that are provided by vkconfig. We have to have the ability to configure the override layers order. For example, the DevSim layer must be "closest to the driver". There are other dependencies as well according to @mark-lunarg .

Although not perfect in the first release, this feature is required by some use cases and has to be included until a new approach can be implemented.

**Comment by christophe-lunarg** [comment]
I think we can deal with these specifics cases with built-in solution by default instead of confusing the users with something impossible to figure out.

For devsim, my plan is to add two configurations:
"Device simulation with validation"
"Device simulation" that exclude validation to prevent the application to validate against the drivers as application controlled layers are executed after overridden layers which are component layers of a implicit layer.

**Comment by mark-lunarg** [comment]
I am confused, does this mean that `within `the set of layers 'managed' by vkconfig, that order cannot be specified by the user?

**Comment by richard-lunarg** [comment]
@mark-lunarg That is correct. This ability was removed. The layers were ordered as the user specified in the layer override, and according to a past conversation with @charles-lunarg, the loader would respect that order. @christophe-lunarg is correct though that if DevSim has to be "next to driver" we should not leave this to the user to do, know about, or mess up. But I think there is some misunderstanding about the utility of the layer order within the vkconfig controlled list. Do you have some example use cases that might help?

**Comment by richard-lunarg** [comment]
Also, @christophe-lunarg may have a very good point about the ordering. Can the layers really be reordered to different effect, or is it just that are there some specific requirements that some layers can't be behind or in front of others. If this is really the case, it should not be left to the user to determine.

**Comment by mark-lunarg** [comment]
The layers can be ordered to different effect.  The tool can offer suggested orderings and/or warn for non-optimal ones, but should absolutely allow arbitrary changes to the layer order.

**Comment by mark-lunarg** [comment]
As a single example, there are common cases where a utility layer might be placed before or after the Khronos layer, according to the desired result.

**Comment by christophe-lunarg** [comment]
With #1165 Vulkan Configurator sorts the layers with what I tried to be the least invasive compared to the Vulkan loader bu design order making adding layers relevant for 99% or more of the users.

But I agreed we need manual ordering of overridden layers (that's the only layers we can order) particularly because the goal is to open Vulkan Configurator to third party layers that we don't know.

The previous implementation was giving a gun to a kid and wishing the kid luck as it didn't represent in what was going on or any helped to the user. It took me reading the Vulkan loader code to understand that and clear myself from the false information I learn because of Vulkan Configurator. The feature was misleading for the 99% of the user that don't care about sorting the layers themselves anyway but would thing they can sort everything but in fact:
- We can't order anything but overridden layers
- We can't order application controlled layers
- Implicit layers are executed first
- Overridden layers are executed within the override layer which may be executed before some implicit layers
- Layers overridden by environment variable are executed between implicit layers and application-controlled layers.

Due to time constraint, the current solution doesn't allow manual sorting of the layers and I am fine with this as we can give a workaround for whoever would be affected and mention that workaround in the "known issues" section of the documentation. However, implementing "manual ordering of overridden layers only" is high priority to me due to the opening to third party layers.

The workaround is simple: Open VkLayer_overriden.json, change the order of the layers in "component_layers" to whatever you need.

**Comment by christophe-lunarg** [comment]
We discussed with Richard about an idea to make a simple UI to reorder only the overridden layers with none of the effect previous observed. I'll try to implement it tomorrow.

**Comment by christophe-lunarg** [comment]
I created a dedicated issue for the manual ordering of overridden layers https://github.com/LunarG/VulkanTools/issues/1169

**Comment by christophe-lunarg** [comment]
This issue is fixed by https://github.com/LunarG/VulkanTools/pull/1165
