### ISSUE TITLE
Replay usability features

### ISSUE THREAD

**Issue by eero-t** [LunarG/VulkanTools#123]
It would be nice if trace replay program would:
* Allow exiting the replay with e.g. ESC or Ctrl-Q key
* Have option for outputting ASCII dump of the trace, similarly to Apitrace "dump" option. I guess this could be easily done with API dump layer?
* When looping, show how many times the loop has been repeated (so that one can estimate how long it has run / will still run)
* Add the required screenshot layer by itself when user requests screenshots, or at least complain if the layer is missing.  It could also tell when/where it saves the screenshot

EDIT: added note about looping & screenshotting

**Comment by ardaLunarG** [comment]
Hey eero-t 

Regarding to ASCII dump of trace file: vktraceviewer (compiles if your have QT5) has the ability to dump to ASCII file and save as txt.
Can you give a try and let us know?

We are planing to add this functionality to command-line as well.

Regarding exiting the replay: do you prefer Ctrl-Q or ESC for graceful exit instead of Ctrl-X?

**Comment by plohrmann** [comment]
The API Dump layer will give more information than saving the trace file to
a text file. At some point during the development of the API Dump later,
the detailed parameter printing was removed from vktraceviewer and moved
into the layer. So now vktraceviewer will only output the same parameter
information that is printed in the UI.

**Comment by eero-t** [comment]
For exiting the replay, any key is fine for me, as long as it's documented.

 If one compares traceviewer API dump to Apitrace trace dump:
* you could add empty line after each present call (as apitrace does after every buffer swap)
* apitrace has option to include line numbers (but I've never needed that)
* apitrace dump includes GLSL shaders code and used pipe line states, but I'm not sure whether showing pipeline state object contents and spirv bytecode would be worth the effort. In the GUI debug tools they should definitely be visible (and editable)

**Comment by eero-t** [comment]
Note: apitrace replay exits with ESC key.

**Comment by eero-t** [comment]
When testing the screenshot functionality, I noticed that the colors in them are too dark (e.g. cube demo background), although colors look fine in replay.  Does this happen also with other than Mesa/Intel Vulkan driver?

**Comment by ardacoskunses** [comment]
Hi Eero,
I have added "exit with ESC key" feature to vkreplay also handling Window close event gracefully so vkreplay errors and crashes minimized (still see some random crashes, working on it) so it helped to github #124 as well.
Additionally added pause/resume functionality to replay with "SPACE" key.
Implementation is Linux only and still work in progress (not reviewed) but if you can test I would appreciate.
Here is the [branch](https://github.com/LunarG/VulkanTools/tree/vkreplayWindowEvents) with my patch.

Remaining items:
Handling resize, Windows implementation and code clean up.

**Comment by eero-t** [comment]
Tried that branch and latest Mesa Git:
* vktrace -p option doesn't produce working trace for smoketest, but server mode does
* There's no crash when closing the replay window from X button or with ESC, either within first repeat or further repeats
* After trace loops, replay outputs a lot of "vkreplay error: event:23" warnings, but they seem harmless

Valgrind still reports the off-by-one reads at startup in vktrace_SettingGroup_Add_Info(), but the issues from exit have gone.

However, there's a new issue reported by Valgrind, a mismatched alloc/free in the exit path:
```
==9117== Mismatched free() / delete / delete []
==9117==    at 0x4C2F24B: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9117==    by 0x411075: vktrace_replay::Sequencer::~Sequencer() (in /home/testrunner/work/VulkanTools/dbuild/vktrace/vkreplay)
==9117==    by 0x410D71: vkreplay_main(int, char**, unsigned int) (vkreplay_main.cpp:398)
==9117==    by 0x410E08: main (vkreplay_main.cpp:558)
==9117==  Address 0xa23a910 is 0 bytes inside a block of size 148 alloc'd
==9117==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9117==    by 0x41724C: vktrace_malloc (vktrace_memory.h:39)
==9117==    by 0x417DFB: vktrace_read_trace_packet (vktrace_trace_packet_utils.c:263)
==9117==    by 0x41171B: vktrace_replay::Sequencer::get_next_packet() (vkreplay_seq.cpp:34)
==9117==    by 0x4102BA: vktrace_replay::main_loop(vktrace_replay::ReplayDisplay, vktrace_replay::Sequencer&, vktrace_replay::vktrace_trace_packet_replay_library**, vkreplayer_settings) (vkreplay_main.cpp:94)
==9117==    by 0x410CAE: vkreplay_main(int, char**, unsigned int) (vkreplay_main.cpp:399
```

After that mismatch is fixed and something's done for the large number of error messages on looping, from my point of view your branch looks ready to be merged.  (I'm just wondering what the ARADA in "ARDA ESC" message means. :-))

**Comment by ardaLunarG** [comment]
Thanks for trying out Eero!

- vktrace -p option doesn't produce working trace for smoketest, but server mode does

This only happens when Json file is missing or pointing to wrong layesrvt file. This patch should **not** cause this. It happens to me also after new checkout and compile. We do not have proper warning for this yet but in TODO list. Could you confirm?

- There's no crash when closing the replay window from X button or with ESC, either within first repeat or further repeats.

That is great, I observe the same, as we stop packages and gracefully exit as we should to do crashes gone.

- After trace loops, replay outputs a lot of "vkreplay error: event:23" warnings, but they seem harmless

Yeah my debug message as this patch still WIP and trying to handle resize

I am getting this error every once a while, I am on it:

==9117== Mismatched free() / delete / delete []
==9117==    at 0x4C2F24B: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9117==    by 0x411075: vktrace_replay::Sequencer::~Sequencer() (in /home/testrunner/work/VulkanTools/dbuild/vktrace/

Yeah sorry for my egotistic debug techniques causing this :) Due to holiday season internal review might take time but I will update you with you the progress.

Thanks again for your review.

**Comment by ardaLunarG** [comment]
Regarding to this comment:
When testing the screenshot functionality, I noticed that the colors in them are too dark (e.g. cube demo background), although colors look fine in replay. Does this happen also with other than Mesa/Intel Vulkan driver?

I have observed the same, captured image somewhat darker than the one the screen.
I have tried different apps. The ones app generates is indeed dark but on the screen it looks light.
During testing we capture a frame during trace and same frame during replay and compare. They generate identical results. 
I will try to dump the content from FB with other techniques (other than screenshot) to see GPU generated image is different or display has an effect on it.

**Comment by eero-t** [comment]
Sorry, I don't have other than Intel HW & Mesa driver with which to test screenshot layer.  Can you test it with something else?

"vktrace -p option doesn't produce working trace for smoketest, but server mode does"

For "cube" demo, the traces produced by "-p" option work fine.  For "smoketest" demo, "-p" option does produce about same sized trace, but replay of that trace file shows just the background color for the smoketest.  Replay works for "smoketest" only when I do tracing of it with server mode.  Do these modes select different defaults?

**Comment by ardaLunarG** [comment]
The problem you are describing indicates PMB for smoketest is not working.
Did you try with --PMB true ? 
I will check if server configuration PMB setting is different.

**Comment by eero-t** [comment]
Yes, "-p ./smoketest" trace done with "--PMB true" works, and with "--PMB false" the trace is broken.

However, with server, the trace is fine even if I start the server with "--PMB false".

**Comment by ardaLunarG** [comment]
Yeah, OK it makes sense. Smoketest is using PMB (persistently mapped buffers) and we set PMB support default off.
We added this functionality for Linux recently but it is not in great shape. We want to keep it on by default once it is better. You can use "--PMB true" for smoketest or you can use Hologram. Hologram is same with smoketest with one difference, it flashed the PMBs so trace and replay works in any case. You can find Hologram in SDK or VulkanSamples repo.

**Comment by eero-t** [comment]
Regarding screenshot darkness... Maybe it's sRGB (=colorspace) issue?

**Comment by ardaLunarG** [comment]
Eero,

For the initial suggestions:
Allow exiting the replay with e.g. ESC or Ctrl-Q key
Note: This is added

Have option for outputting ASCII dump of the trace, similarly to Apitrace "dump" option. I guess this could be easily done with API dump layer?
Note: Did you try this on vktraceviewer to dump the apitrace?

When looping, show how many times the loop has been repeated (so that one can estimate how long it has run / will still run)
Note: This is added

Add the required screenshot layer by itself when user requests screenshots, or at least complain if the layer is missing. It could also tell when/where it saves the screenshot
Notes: screenshot layer is standalone now.

Remaining items: complain if layer is missing and location and name of the screenshot file.
Needs to be implemented.
Regarding to screenshot darkness:
On other drivers besides Intel we do not see this issue.
But I did not dig in for technical details for this.
If you think this is a screenshot issue, could you file a separate bug so we can make sure it is addressed correctly.

**Comment by eero-t** [comment]
> Allow exiting the replay with e.g. ESC or Ctrl-Q key
> Note: This is added
>
> When looping, show how many times the loop has been repeated (so that one can estimate how long it has run / will still run)
> Note: This is added

Thanks, verified both!


> Have option for outputting ASCII dump of the trace, similarly to Apitrace "dump" option. I guess this could be easily done with API dump layer?
> Note: Did you try this on vktraceviewer to dump the apitrace?

Sure, but the problem with that is that it pages the whole trace into memory when it starts, and if your trace is larger than what you have RAM, things are crawling while it's busy poisoning OS page cache.  

As all it requires is setting an environment variable (in the program itself or wrapper script for it), it's trivial thing to add.  I of course have a script for that, but I thought it would be nice in replay itself too.  Feel free to ignore this request. :-)

> Regarding to screenshot darkness:
> On other drivers besides Intel we do not see this issue.
> But I did not dig in for technical details for this.
> If you think this is a screenshot issue, could you file a separate bug so we can make sure it is addressed correctly.

Added bug #153.


> Remaining items: complain if layer is missing and location and name of the screenshot file.
> Needs to be implemented.

Ok, once's these are done, from my point this ticket can be closed.

**Comment by ardaLunarG** [comment]
Thanks Eero,
I will close this ticket and open a new one for:
"complain if layer is missing and location and name of the screenshot file."
