### ISSUE TITLE
vkconfig: Bad stdout log file specification on macOS

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1262]
On macOS, when starting from a clean slate (no previous vkconfig files present), the output from the Khronos Standard validation is not set to stdout, but rather:
/Users/<user account>/vulkan-sdk/stdout

Edit, this also happens with the API dump. It seems that when a fresh config is manufactured, the default log output is set incorrectly here. This does not occur on Windows.

Edit 2: It seems if I edit these fields and make them stdout, the changes only last while vkconfig is running. When I close and restart vkconfig, their values are again set toe /User/LunarG/vulkan-sdk/stdout

See screen shot below:
![image](https://user-images.githubusercontent.com/58573781/101223963-499ecd80-365b-11eb-8ab1-f16424508303.png)

**Comment by richard-lunarg** [comment]
I've determined this regression was introduced by Qt 5.15.2, and Qt 5.13.2 which is used for SDK builds does not reproduce this error. We still need to figure out why this occurs with a newer Qt build, but it is not highest priority.

**Comment by christophe-lunarg** [comment]
I am guessing this issue is workaround thanks to this PR: https://github.com/LunarG/VulkanTools/pull/1265

It's this code that insert "vulkan-sdk" path. Even if the path it stored incorrectly, the path should be updated to use stdout.

This said, it's probably a terrible practice to use magic values to output to stdout and stderr and it's an inconsistent practice with others layers at the very least.

**Comment by christophe-lunarg** [comment]
This said, this issue doesn't reproduce for me with Qt 5.15.1
