### ISSUE TITLE
vkconfig: can't select "User-Defined Settings" "preset"

### ISSUE THREAD

**Issue by johnzupin** [LunarG/VulkanTools#1297]
Choose "User-Defined Settings" and it will revert to the second selection in the drop-down. 

![Peek2020-12-21 10-00](https://user-images.githubusercontent.com/3836693/102802062-5ae21c80-4373-11eb-9dd2-49e49fbeb0a9.gif)

**Comment by christophe-lunarg** [comment]
This one is pretty difficult to change and valid for all presets. This is because the field is updated base on the actual settings. If the settings match a preset then, this preset label is used.

I might change the behavior for next release but this is a bunch of work so too risky for this release.

**Comment by christophe-lunarg** [comment]
This issue is resolved with the version in SDK 1.2.176.
