### ISSUE TITLE
vkconfig: A 'VulkanSDK' directory is created in the user's home directory without any notification

### ISSUE THREAD

**Issue by johnzupin** [LunarG/VulkanTools#1299]

**Comment by johnzupin** [comment]
Looks like vkconfig created a directory directly in the home folder and copies over portability json files:
```
VulkanSDK/
└── share
    └── vulkan
        └── config
            └── VK_LAYER_LUNARG_device_simulation
                ├── iOS_gpu_family_3_portability.json
                ├── iOS_gpu_family_5_portability.json
                └── macOS_gpu_family_1_portability.json
```
Would it be best to use the `.local/share/vulkan/` directory instead? Does a folder with these files need to be copied over at all instead of using them directly from the repo/SDK/system path? If not, a notification that vkconfig is creating a directory directly in the home folder might be warranted to avoid any confusion.

**Comment by christophe-lunarg** [comment]
This issue should be fixed with this PR https://github.com/LunarG/VulkanTools/pull/1302

This said, there is still a VulkanSDK directory systematically created for log file and gfxrecon capture.

Maybe in the future we should actually have a $HOME/VulkanSDK/Config directory so that users could easily add new configurations but will be future work.

**Comment by johnzupin** [comment]
Maybe this is a separate issue but should the folder be named "VulkanSDK"? Maybe it should be "Vkconfig" or something similar? I'm just thinking that there could be confusion that the SDK installer is creating this folder.
