### ISSUE TITLE
vkconfig: Provide import mechanism from GPUinfo.org of profiles

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#1301]
Over time, as gpuinfo.org gets populated with more Apple devices, there will be devsim configuration files that are not included in the Vulkan SDK. It would be very useful for an individual to download a configuration file from gpuinfo.org and import it into the directory in the Vulkan SDK so that they are discoverable by the Vulkan Configurator.

**Comment by christophe-lunarg** [comment]
Notice that also it will be populated with more Apple devices, it doesn't necessary imply more different devsim configuration files. It's going to be a lot of the same devsim configuration files until Metal API add supports a feature that Vulkan support already.

I am mentioning this because I am concerned that "download a configuration file from gpuinfo.org" that @SaschaWillems give us access to GPUInfo.org database somehow which could require a significant development cost both Sascha and us.

@SaschaWillems if you have an idea about this topic, your input is welcome !

**Comment by SaschaWillems** [comment]
I'm open for suggestions on this :) I already implemented different APIs for the database upon request, and adding another one for providing devsim files on a convenient way is an option. An alternative would be a cronjob that gathers unique devsim JSON files per platform and then uploads them to some location accessible by vkconfig and/or developers.

**Comment by christophe-lunarg** [comment]
The profiles layer was modified to be able to load all the profiles from a directory. Application developers can download all the GPUinfo.org in that directory and these profiles will be picked up. This seems enough for the purpose of the integration with GPUinfo.org.
