### ISSUE TITLE
devsim: how to disable extension

### ISSUE THREAD

**Issue by pc-john** [LunarG/VulkanTools#1415]
Hi,

I googled everywhere but I was not lucky to find how to disable one particular extension (in my case VK_EXT_line_rasterization) by devsim and test my application whether it is still running correctly.

Is it possible to disable extensions by devsim? Would it be possible for you to give an example json file? Or, even better, could such example be put, for instance, on https://github.com/LunarG/VulkanTools/blob/master/layersvt/device_simulation.md ?

Thanks. This would be extremely useful for me.

**Comment by jeremyk-lunarg** [comment]
In the [Device Simulation Manual](https://github.com/LunarG/VulkanTools/blob/master/layersvt/device_simulation.md) under the [Devsim Layer Operation and Configuration](https://github.com/LunarG/VulkanTools/blob/master/layersvt/device_simulation.md#devsim-layer-operation-and-configuration) section there is a list of devsim schemas and a list of config file parameters.  Third from the bottom of the parameter list is `ArrayOfVkExtensionProperties` which can modify and disable device extensions.

Unfortunately, this parameter replaces the entire device extension list, so it must be turned on with the `VK_DEVSIM_MODIFY_EXTENSIONS_LIST` environment variable, or its equivalent setting `lunarg_device_simulation.modify_extension_list`, mentioned in the [Devsim Layer Options](https://github.com/LunarG/VulkanTools/blob/master/layersvt/device_simulation.md#devsim-layer-options).

As for an example JSON file, it would look something like this:
```
{
    "$schema": "https://schema.khronos.org/vulkan/devsim_1_2_0.json#",
    "comments": {
    "desc": "Example use of ArrayOfVkExtensionProperties."
    },
    "ArrayOfVkExtensionProperties": [
        {
            "extensionName": "VK_KHR_acceleration_structure",
            "specVersion": 11
        },
        {
            "extensionName": "VK_KHR_push_descriptor",
            "specVersion": 2
        },
        {
            "extensionName": "VK_KHR_swapchain",
            "specVersion": 2
        },
        {
            "extensionName": "VK_EXT_custom_border_color",
            "specVersion": 12
        },
        {
            "extensionName": "VK_EXT_shader_atomic_float",
            "specVersion": 1
        }
    ]
}
```

Notice that the array uses `[ ]` to encapsulate its items instead of `{ }`.
Always remember to validate your JSON files against whatever schema you are using at a trusted JSON validator such as https://www.jsonschemavalidator.net/

In the future, we are looking to improve how devsim modifies arrays of things on the device.

**Comment by pc-john** [comment]
Thanks!
Using your example and putting only four essential extensions for my app while not putting VK_EXT_line_rasterization really worked! Devsim is so helpful tool for debugging!
