### ISSUE TITLE
vktrace -p option doesn't work

### ISSUE THREAD

**Issue by eero-t** [LunarG/VulkanTools#151]
Setup:
- HW: SKL GT2
- OS: Ubuntu 16.04 with all the updates
- SW: Latest VulkanTools & Mesa from git

Use-case:
- vktrace -p ./cube -o cube.vktrace

Expected result:
- cube.vktrace trace file, like one gets when running vkrace as server and giving the required environment variables separately to "cube"

Actual result:
- No trace file, but no error either, cube itself runs fine

Notes:
- vktrace seems to set all the required environment variables, so problem is somewhere else:
```
$ tr '\0' '\n' < /proc/$(pidof cube)/environ |grep VK
VK_ICD_FILENAMES=/usr/local/share/vulkan/icd.d/intel_icd.x86_64.json
_VK_TRACE_VERBOSITY=errors
_VK_SCREENSHOT=
_VKTRACE_OPTIMIZE_PMB=1
VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_vktrace
VK_DEVICE_LAYERS=VK_LAYER_LUNARG_vktrace
```

(I'm fine with removing "-p" option, there shouldn't be non-working options.)

**Comment by ardaLunarG** [comment]
Eero,
Are you saying when you run vktrace in app mode (non-server) your trace file is not generated?

I run vktrace with -p option all the time and seldom using server mode. 
I just tried to reproduce the issue and confirm -p is working fine for me.
Also we do trace/replay testing for each commit, and test working with -p.

Most of the time, this happens when vktrace layer cannot be found. Json files is the first place to check.
However from your environment variables I can see vktrace layer found. This output is from server or with -p mode?

Could you please double check the json is finding right vktrace layer and maybe try -w option to point vktrace the working directory?

**Comment by ardaLunarG** [comment]
Eero,

Just checked my environment vars:
**VK_LAYER_PATH=/home/arda/workspace/VulkanTools/dbuild/layersvt**
_VK_TRACE_VERBOSITY=errors
_VK_SCREENSHOT=
_VKTRACE_OPTIMIZE_PMB=1
VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_vktrace
VK_DEVICE_LAYERS=VK_LAYER_LUNARG_vktrace

The highlighted seems like your missing piece where vktrace json file resides.

**Comment by eero-t** [comment]
Thanks and sorry for the noise.  Closing as user-error.

Could tools output something if the required layer(s) cannot be loaded?

**Comment by ardaLunarG** [comment]
Hi Eero,

Unfortunately this happens quite often: when vktrace layer missing, app works normally and vktrace does not complain even tracefile is not generated.
On Windows this could be detected as threads communicate back.
On Linux due to pthread implementation we could not see this is happening.

The plan is implementing a watchdog like thread in vktrace app side and check if the trace file is getting written to.

However this could happen due to various reasons:
1- vktrace layer is missing
2- App does something else other than calling Vulkan APIs
3- App forks/execs another process which makes Vulkan API calls
So if trace file is not growing in time we plan to print a warning to warn user to check if one these 3 cases happening. 

Work in progress.

**Comment by eero-t** [comment]
At first, it might give this warning only at the end when child exits, if the trace file didn't appear.
