### ISSUE TITLE
VK_LAYER_PATH for both 32-bit and 64-bit

### ISSUE THREAD

**Issue by Overv** [LunarG/VulkanTools#156]
I noticed that there is only one `VK_LAYER_PATH` environment variable (on Windows at least). I can either point it to the `Bin` or the `Bin32` directory in the SDK to support either 32-bit or 64-bit builds.

What do I need to do if I want to do both? Shouldn't there be a separate variable for one of the two architectures?

**Comment by lenny-lunarg** [comment]
If you're using the Windows SDK, then you probably shouldn't be using `VK_LAYER_PATH` at all. The loader searches the Windows registries for available layers, and this should be the preferred way of locating layers. `VK_LAYER_PATH` is intended as an easy way to override that behavior, useful mainly for developing layers or testing different layers, but not for general use of the layers. To find the full behavior, [read the documentation](https://vulkan.lunarg.com/doc/sdk/1.0.39.0/windows/layers.html) we have on this behavior. In particular you want the `Configuring Layers on Windows` and `Activating Layers on Windows` sections. The one detail that the documentation doesn't mention, is that Windows maintains separate 64-bit and 32-bit registries, and that the loader will automatically find the correct one. This means that the registries identify 64-bit layers and 32-bit layers easily.

But even if you want to use `VK_LAYER_PATH` for some reason (and there are some good reasons to do this), it's not hard to set up. If you're using Visual Studio, there's an option to debug programs with given environment variables, which can be changed depending on the build type. Most other IDE's will have similar functionality, and it also takes only one line to change the value in a command prompt (`set VK_LAYER_PATH=C:\VulkanSDK\1.0.39.0\Bin`). You just won't want to set the value for your entire OS.

Also, this isn't really the right place for this issue. The loader and layers are (mostly) written in [Loader And Validation Layers](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers), so that's where any code changes would have to be made if there was a reason for them, and for SDK-specific issues we mostly use [LunarXchange](https://vulkan.lunarg.com/issue/home).
