### ISSUE TITLE
Developer can't use configurator to run API trace layer on Windows

### ISSUE THREAD

**Issue by null77** [LunarG/VulkanTools#1632]
I'm using the 2.4.2 configurator on Windows, API dump layer is listed as 1.2.198. I'm getting this error in the loader logs:

```
WARNING: verify_meta_layer_component_layers: Meta-layer VK_LAYER_LUNARG_override can't find component layer VK_LAYER_LUNARG_api_dump at index 0.  Skipping this layer.
DEBUG: Removing meta-layer VK_LAYER_LUNARG_override from instance layer list since it appears invalid.
```

Full log attached. Any idea what could be causing this issue? I'd like to trace the Vulkan API calls.

[configurator-log.txt](https://github.com/LunarG/VulkanTools/files/7884071/configurator-log.txt)

**Comment by charles-lunarg** [comment]
I am not sure what is going on because the log message stems from the layer not being found in the list of available layers. Looking through the log it is clear that API Dump is found at one point, but not at the next point. One thought that comes to mind is the setting of environment variables like `VK_LAYER_PATH` which overrides the default explicit layer search paths, which api_dump appears to be in. 

This could of happened in between the calls to `vkEnumerateInstanceLayer/ExtensionsProperties` and `vkCreateInstance`.

**Comment by null77** [comment]
Yeah, my bad, this is likely because of an interaction with VK_LAYER_PATH.
