### ISSUE TITLE
VKConfig Profiles doesn't allow a path only allows selecting a profile JSON but then you still select the Profile in a combo box

### ISSUE THREAD

**Issue by MarkY-LunarG** [LunarG/VulkanTools#1647]
![profile_selection_options](https://user-images.githubusercontent.com/16328578/153271838-4e74e689-7d9c-4b48-a6d3-56b83eebdc8c.png)

It seems to me that either you have the top combo box only, or a path and the top combo box.  Having the top combo box, plus a path to the file, plus another combo box to select the same profile seems very confusing to me and prone to issues for end users.

**Comment by christophe-lunarg** [comment]
Erm, I didn't understand the issue. I can agree that the UI is not very nice but I would not know how to change it... 
Maybe removing the path but in that case we can't just copy pass a path to load profiles...

**Comment by christophe-lunarg** [comment]
Maybe a confusion was that a single Vulkan profiles file may contain multiple profile definition.

This issue was probably more a Vulkan Profiles layer setting issue. 

I refactored the settings so that we clearly separate the loading of available profiles and the selection of a profile.
Now, we select a directory where to find the profiles files, then a combo-box list all available profiles that can be selected.

If you have further comments / questions / complains, feel free to reopen the issue!
