### ISSUE TITLE
apidump causes deadlock by holding mutex on down-chain calls

### ISSUE THREAD

**Issue by mikes-lunarg** [LunarG/VulkanTools#1718]
Running https://github.com/KhronosGroup/Vulkan-Samples/tree/master/samples/extensions/timeline_semaphore and I get a deadlock when trying to use `VK_LAYER_LUNARG_api_dump`. Appears to be caused by the layer holding `outputMutex` during the call to the driver. The sample app waits on a timeline semaphore in one thread while submitting a signal operation in another--but the signal never gets submitted because the wait is holding the lock.

I'm not sure what the correct thing to do here is, since this behavior looks like it was introduced in response to other issues: #791 #932

**Comment by charles-lunarg** [comment]
So the gist of why api dump holds the mutex is because it outputs the called function name *before* calling into the driver, ensuring that if the call never returns, the dump contains the failed function call, rather than showing the call before it. It was assumed that any Vulkan API call would always return, and not deadlock. This assumption is obviously false (just never been an issue until now).

What could be done is special casing any function that is likely to wait, then change the code to not write anything before the vulkan call is made. Effectively revert to the previous api dump behavior for functions which could cause deadlocks.

Waiting functions include:
* `vkWaitForFences` 
* `vkWaitSemaphores`

(If you know of any more, please mention them)

**Comment by mikes-lunarg** [comment]
Seems like a reasonable workaround. I would add the following functions which are called out as potentially blocking in https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#devsandqueues-lost-device:
- `vkDeviceWaitIdle`
- `vkQueueWaitIdle`
- `vkAcquireNextImageKHR`
- `vkGetQueryPoolResults`
