### ISSUE TITLE
vkconfig caching bug

### ISSUE THREAD

**Issue by juan-lunarg** [LunarG/VulkanTools#1797]
vkconfig caches the value of `VULKAN_SDK` during a tarball run. Which can cause issues for users in niche situations.

Repro steps:

```
$ export VULKAN_SDK='1.4.293'
$ printenv | grep -i vulk
VULKAN_SDK=1.4.293 # verify it was set correctly

# Run and close vkconfig
$ vkconfig

$ unset VULKAN_SDK
$ printenv | grep -i vulk $ verify it was removed

# Re-run vkconfig and obverse it uses the old value likely due to some sort of caching
$ vkconfig
```

Here is vkconfig using a stale/invalid VULKAN_SDK environment variable.

![image](https://user-images.githubusercontent.com/114601453/221255799-b1b5d088-6aa2-43e8-944e-5b0b4a9f504a.png)

**Comment by juan-lunarg** [comment]
Note this issue still persists:

![image](https://user-images.githubusercontent.com/114601453/231907098-c98ea28c-9957-4a9e-9287-89ec9dd08dee.png)

Any thoughts on how I can tackle this @christophe-lunarg ?

**Comment by christophe-lunarg** [comment]
No idea and I don't believe it really matters.

**Comment by absolutelynothelix** [comment]
i encountered this issue as well. it seems that if vkconfig sees that the `VULKAN_SDK` environment variable is set it caches it into the `LunarG/vkconfig.conf` file (the `vulkan_sdk` line) and reads it from there if it's not set.

1) i'm not sure if it's used at all because in my case it was pointing to an obsolete non-existent directory;
2) i'm not sure if it's right to call an environment variable something that's read from a file.

also, while trying to figure out where it comes from i noticed that the `else` block here may be useless because the `search_path` variable seems to default to the home directory if the `VULKAN_SDK` environment variable is not set and the `vulkan_sdk` line in the `LunarG/vkconfig.conf` file is empty:
https://github.com/LunarG/VulkanTools/blob/5b5f250086a8f82827d3e07f41d0511c8d84bdb4/vkconfig/vulkan_util.cpp#L168-L173
