### ISSUE TITLE
API dump layer does not compile with latest Vulkan headers

### ISSUE THREAD

**Issue by vonture** [LunarG/VulkanTools#2088]
The latest Vulkan headers (commit https://github.com/KhronosGroup/Vulkan-Headers/commit/595c8d4794410a4e64b98dc58d27c0310d7ea2fd) removed the enum `VkVideoEncodeFlagBitsKHR` which causes compilation errors in the API dump layer:

```
In file included from [...]/layersvt/generated/api_dump.cpp:27:
[...]/layersvt/generated/api_dump_text.h:11576:41: error: unknown type name 'VkVideoEncodeFlagBitsKHR'; did you mean 'VkVideoEncodeFlagsKHR'?
11576 | void dump_text_VkVideoEncodeFlagBitsKHR(VkVideoEncodeFlagBitsKHR object, const ApiDumpSettings& settings, int indents)
|                                               ^~~~~~~~~~~~~~~~~~~~~~~~
|                                               VkVideoEncodeFlagsKHR
```

**Comment by charles-lunarg** [comment]
Generally, this repo expects to be built against a specific header version (specified in known_good.json). 

That said - it is pretty unusual that updating to newer headers breaks the build. The fix is thankfully extremely simple - just update this repo to the latest headers (which involves running the code gen).

I'm going ahead and doing just that to unblock you.

**Comment by charles-lunarg** [comment]
Closing since the header updates fixed the issue (I did repro it) and it has been merged.
