### ISSUE TITLE
vkconfig3: Text hard to read

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#2187]
The bright blue is very hard to read when the Mac is in dark mode.

<img width="540" alt="image" src="https://github.com/user-attachments/assets/66ce1c91-5fb1-4d05-9642-846a32c122e7">

**Comment by christophe-lunarg** [comment]
A difficulty is that dark mode support is pretty new in Qt.

Here is a code example that could be useful in the future:
```
#include <QGuiApplication>
#include <QPalette>
#include <QStyleHints>

inline bool isDarkMode() {
#if QT_VERSION >= QT_VERSION_CHECK(6, 5, 0)
  const auto scheme = QGuiApplication::styleHints()->colorScheme();
  return scheme == Qt::ColorScheme::Dark;
#else
  const QPalette defaultPalette;
  const auto text = defaultPalette.color(QPalette::WindowText);
  const auto window = defaultPalette.color(QPalette::Window);
  return text.lightness() > window.lightness();
#endif // QT_VERSION
}
```

**Comment by richard-lunarg** [comment]
Have you considered bumping up to Qt6 for version 3?

**Comment by christophe-lunarg** [comment]
> Have you considered bumping up to Qt6 for version 3?

Would this be reasonnable? Specifically regarding the Ubuntu linux distro we support?

**Comment by richard-lunarg** [comment]
Yes, we are up to Qt 6.6 now, and it is available on Linux as well. Ubuntu, Raspbian, etc.

**Comment by christophe-lunarg** [comment]
I resolved this issue by copying dynamically to the text color to the <a> html tag:
![image](https://github.com/user-attachments/assets/e66d0f3d-f27d-427a-a16e-8af72a8d5de5)

It turns out that themes would have not resolved this. Not sure how this is typically handled...

This is resolved here: https://github.com/LunarG/VulkanTools/pull/2205 but it's a pretty tedious solution. :/
