### ISSUE TITLE
Tracing and replaying vkCreateBuffer needs to handle valid structures in pNext

### ISSUE THREAD

**Issue by Tony-LunarG** [LunarG/VulkanTools#226]
VK_STRUCTURE_TYPE_DEDICATED_ALLOCATION_BUFFER_CREATE_INFO_NV and
VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO_KHX are valid sType structures for pNext to point to in vkCreateBuffer and currently at playback, the pNext address from the trace file is not remapped and usually playback crashes.  The vkCreateImage call seems to handle this, it just needs to be extended to vkCreateBuffer

**Comment by davidlunarg** [comment]
This problem was probably found from tracing/replaying Talos Principle. If we can trace/replay this game, we can close this issue.

**Comment by davidlunarg** [comment]
pNext structures during tracing of vkCreateBuffer are handled in the call to vktrace_add_pnext_structs_to_trace_packet in the the function VKAPI_CALL__HOOKED_vkCreateBuffer in file vktrace_lib_trace.cpp.

pNext structures during replay of vkCreateBuffer are handled in the call to vktrace_interpret_pnext_pointers from interpret_body_asVkCreateBuffer in the generated file vktrace_vk_vk_packets.h, which is is called from interpret_trace_packet_vk, which is called from vkReplayInterpret, which is call from main_loop in vkreplay_main.cpp.

This issue was fixed when enhancements were made to vktrace/replay for handling additional entry points and more use of pNext structures in Vulkan 1.1.
