### ISSUE TITLE
Vulkan LunarG samples exits without any passing status/info on Linux

### ISSUE THREAD

**Issue by manishashirke** [LunarG/VulkanTools#243]
Bellow samples on linux exits without any pass/fail info, also no rendering on screen.
01-init_instance
02-enumerate_devices
03-init_device
04-init_command_buffer
05-init_swapchain
06-init_depth_buffer
07-init_uniform_buffer
08-init_pipeline_layout
09-init_descriptor_set
10-init_render_pass
11-init_shaders
12-init_frame_buffers
13-init_vertex_buffer
14-init_pipeline
create_debug_report_callback

**Comment by karl-lunarg** [comment]
Correct, these programs don't have pass/fail info and they don't draw anything on the screen.  This is by design.  These programs are meant to accompany a tutorial found in https://github.com/LunarG/VulkanSamples.  (These programs and the tutorial are found in the VulkanSamples repo and not in this VulkanTools repo, which means that this issue is in the wrong repo.)

These programs are not meant to be part of an automated tests library or anything like that.  And, as the tutorial explains, the programs are progressive and build up Vulkan concepts until there is enough in place to draw something, which doesn't happen until the last program in the set.

If you think that something more needs to be done here, please open a new issue in the VulkanSamples repo, preferably after looking at the tutorial so that you understand the programs' purpose.
