### ISSUE TITLE
vktrace:  Why page guard is disabled on Android?

### ISSUE THREAD

**Issue by justuswang** [LunarG/VulkanTools#301]
Is it possible to enable page guard on Android?  Some application may not be traced correctly on Android platform without page guard.

**Comment by cnorthrop** [comment]
Mostly because it hasn't been staffed.  If you have time to do it, that would be fantastic.  We can't use the Linux solution directly due to lack of `/proc/self/pagemap`.  Although that is just an optimization - should be able to get it working without.

I had some early exploration of it on the [pmb_hacks](https://github.com/LunarG/VulkanTools/tree/pmb_hacks) branch, but wasn't able to finish it.  I believe I was trying to use exceptions to detect when a page had been modified, but I was getting a ton of false positives (exceptions on pages that weren't from the application).  I believe the smoke demo was working on that branch, but not Talos Principles, the other known app that required it.

**Comment by justuswang** [comment]
Thanks for your answers.

But I still have a question:
I have found that /proc/self/pagemap exists on Android system (at least on Android M).  Is it different from the /proc/self/pagemap on Linux OS or not accessible by the trace layer on Android?

**Comment by justuswang** [comment]
This issue has been addressed by https://github.com/LunarG/VulkanTools/pull/397
