### ISSUE TITLE
update_external_sources.sh fails.

### ISSUE THREAD

**Issue by yousry** [LunarG/VulkanTools#31]
Error message:

CMake Error at CMakeLists.txt:52 (string):
  string sub-command REPLACE requires at least four arguments.

I'm using:
cmake version 3.5.2

**Comment by karl-lunarg** [comment]
This is probably due to a failure in the llvm-config call a few lines before line 52.

```
execute_process(COMMAND ${LUNARGLASS_PREFIX}/Core/LLVM/llvm-3.4/${BUILDTGT_DIR}/install/usr/local/bin/llvm-config --cxxflags
  OUTPUT_VARIABLE LLVM_CXX_CONFIG_ALL_1
  RESULT_VARIABLE LLVM_CXX_CONFIG_RESULT)

string(REPLACE "\n" "" LLVM_CXX_CONFIG_ALL ${LLVM_CXX_CONFIG_ALL_1})
string(REPLACE "-Woverloaded-virtual" "" LLVM_CXX_CONFIG_1 ${LLVM_CXX_CONFIG_ALL})
string(REPLACE "-fvisibility-inlines-hidden" "" LLVM_CXX_CONFIG ${LLVM_CXX_CONFIG_1})
message(STATUS "llvm-config cxxflags results")
message(STATUS ${LLVM_CXX_CONFIG})

# if(NOT "${LLVM_CXX_CONFIG_RESULT}" EQUAL "0")
#   message(FATAL_ERROR "llvm-config failed: " ${LLVM_CXX_CONFIG_RESULT})
# endif()


```
A failure in the `execute_process()` would probably result in `LLVM_CXX_CONFIG_ALL_1` not getting set, which would make cmake think that there were only three arguments.

So there may have been a problem with building llvm in the update_external_sources step.  You might try uncommenting the last three lines to see if llvm-config result is useful.
