### ISSUE TITLE
api_dump does not dump vkCreateDevice parameters/results when vkCreateDevice returns an error

### ISSUE THREAD

**Issue by jcoder58** [LunarG/VulkanTools#43]
I have the api_dump layer enabled in both the instance and the VkDeviceCreateInfo enabled layers, however the call is not reported.  Other calls make prior to the vkCreateDevice  call are dumped correctly.   When I fix the issue with vkCreateDevice so that it returns success, it is dumped correctly.

**Comment by karl-lunarg** [comment]
Are saying that api_dump quits working if vkCreateDevice fails?

**Comment by jcoder58** [comment]
Yes.  It quits working and does not dump the vkCreateDevice call at all.

**Comment by karl-lunarg** [comment]
OK, thanks.   (Sorry, sometimes I don't combine the bug's Subject line with the description)  We can see the value in having this work even if a vulkan call fails, to help debugging.  We'll have to look at the implementation to see if there's any reason why api_dump cannot continue on in this case.

**Comment by MarkMLunarG** [comment]
According to the code that I am looking at, vkCreateDevice always dumps information, whether the command fails or not. On the other hand vkCreateInstance says nothing upon failure. Are you sure you mean vkCreateDevice and not vkCreateInstance? I do have a fix available for the later, but don't see a problem with the former

**Comment by MarkMLunarG** [comment]
Please see PR #47

**Comment by jcoder58** [comment]
Just verified that it is VkCreateDevice.  You can duplicate it by passing a bad extension name to vkCreateDevice (I used "yyy").

**Comment by olvaffe** [comment]
Bad extension names are likely rejected by the loader, before any validation layer kicks in.

**Comment by jon-lunarg** [comment]
Yes I would not expect api_dump layer to ever get called  for CreateDevice with a bad extension name.

**Comment by karl-lunarg** [comment]
jcoder58:  When vkCreateDevice is called with an invalid extension, it returns VK_ERROR_EXTENSION_NOT_PRESENT.  Jon is correct in that no further calls are made down the layer/device chain under these conditions, so a layer like api_dump would not be called.

It seems that the VK_ERROR_EXTENSION_NOT_PRESENT is a specific enough return code to direct the programmer to examine the extension list for a problem

Is this sufficient to address your issue?

I think that the most we could do otherwise is to change the loader code to log a message that could list the "yyy" extension as not being found.  Then, you could set VK_LOADER_DEBUG=all to see this diagnostic message.

A layer like api_dump might not be expected to handle cases where fundamental calls like CreateInstance or CreateDevice fail.  In this case, the loader cuts it off completely.

**Comment by jcoder58** [comment]
Karl:  I'm a beginner with Vulkan and am also writing code in C#.  This requires marshaling strings from C# string value to a C null terminated string.  So having the dump of the failed call would have helped me make sure I was transforming the strings correctly.    

Also, not having the dump made me question whether the error return was correct.  I wondered if I had corrupted something or had some other failing that caused it to report an incorrect error.  The error I had was that I had swapped the layers and the extensions parameters and so I could see I was passing in correct strings, just in the wrong order.  This was due primarily to my complete lack of experience with Vulkan.

If there isn't a log message that provides additional info about the  VK_ERROR_EXTENSION_NOT_PRESENT, there should be.   It would have helped me in this case as I had enabled the DebugCallback.    Will this help with VkCreateInstance errors as well?  Can a DebugReportCallback be setup prior to a VkCreateInstance call?

**Comment by jon-lunarg** [comment]
A DebugReportCallback can be setup during vkCreateInstance by passing the callback information in the CreateInfo pNext field. See the VK_EXT_debug_report specification for details.  In addition to this callback, you would want to enable validation layers (VK_LAYER_LUNARG_standard_validation) instead of api_dump layer for an application that is in development and likely has bugs. Perhaps you were doing that already?

In spite of all of the above, validation of vkCreateDevice and vkCreateInstance could be improved. This validation is a bit tricky since part of it is difficult or impossible, part of it must be done in the loader and part of it can be done in validation layers

**Comment by karl-lunarg** [comment]
The relevant part of the spec concerning supplying a DebugReportCallback for CreateInstance is:

> To capture issues found while creating an instance an application can link a VkDebugReportCallbackCreateInfoEXT structure to the pNext element of the VkInstanceCreateInfo structure given to vkCreateInstance. This callback is only valid for the duration of the vkCreateInstance call. Use vkCreateDebugReportCallbackEXT to create persistent callback objects.

Since the question of having additional messaging for failed CreateDevice requests lies in the loader and layers, I'll open a new issued for that in https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers.   There's nothing further to do in api_dump, so I am closing this issue.
