### ISSUE TITLE
VK_LAYER_LUNARG_api_dump: Show Image handle next to ImageView handle

### ISSUE THREAD

**Issue by tobine** [LunarG/VulkanTools#451]
From @RCalocaO, moving from [LVL](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2568) to here.

When showing information for ImageViews (outside of creation, eg vkUpdateDescriptorSets), it would be extremely useful to have its associated Image next to it, would simplify searching dumps of more than 1 million lines, eg:
pDescriptorWrites[6]: const VkWriteDescriptorSet = 0000024297701780:
sType: VkStructureType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET (35)
pNext: const void* = NULL
dstSet: VkDescriptorSet = 000000000000077D
dstBinding: uint32_t = 1
dstArrayElement: uint32_t = 0
descriptorCount: uint32_t = 1
descriptorType: VkDescriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER (1)
pImageInfo: const VkDescriptorImageInfo* = 0000024296196480
pImageInfo[0]: const VkDescriptorImageInfo = 0000024296196480:
sampler: VkSampler = 000000000000000D
imageView: VkImageView = 0000000000000700 **(VkImage = 000000000006FF)**
imageLayout: VkImageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL (5)

**Comment by karl-lunarg** [comment]
To be clear, I think that the ask is to add the text that I emboldened in the first comment of this issue.

Not saying"no" just yet, but wouldn't this require tracking all image views and a map from the handles to those views?

api_dump is not a state tracker and is intended to just dump the api calls.

And if this is done for image views, what about other things like showing the buffer handle whenever a buffer view is referenced?  And so on...

**Comment by lenny-lunarg** [comment]
Like Karl said, API dump was never intended to track state. That doesn't necessarily mean that this can't or shouldn't be done. But it does mean that it will be a bit of a pain, since there's basically no infrastructure in API dump to support state tracking as it is now.

If we were to decide that it's worth it we could always just bite the bullet. But my point is that we would definitely need a bit of work to support this.

**Comment by mark-lunarg** [comment]
I'd be wary of building this kind of stuff into apidump, but it'd be perfect for a GUI-based dump post-processing tool -- maybe it could look something like apitrace.  That'd be super-useful.

**Comment by karl-lunarg** [comment]
Yes, I'd be more in favor of a separate tool for this sort of thing, although I do recognize the possible confusion with having separate tools doing almost the same thing.

I'm really against building a GUI api dump browser that would parse the current api dump text output.  Doing so creates a dependency between the tools and makes it hard to change api dump.  It is also pretty hard to write a parser that would do this and remain usable if api dump makes even cosmetic changes in its output.

Another approach would be to add the capability to api dump (runtime option or different layer) that would serialize the api calls to a parsable format like JSON.  Then write a browser that works a bit like a web browser does when looking at HTML vulkaninfo output, letting you expand and collapse structures.  This browser would do the state tracking being asked for here to enable drilling down through some objects to display more info.

And we do have vktraceviewer, which already does a lot of this.  It only displays (via a tooltip) the first-level arguments.   But it _could_ be improved into a tool that displays a deeper expansion of the current API call, including spelunking into state-tracked data structures to fetch interesting handles, etc.  In this workflow, the user would create the trace file with vktrace.  No need for a new trace file format or generating layer.  The vktraceviewer work would consist of a new "pane" that displays the deep parameter info for the current/selected API Call.

But if @RCalocaO just wants a better-annotated api dump text file, then we're back to doing a state-tracking version of api dump.

**Comment by charles-lunarg** [comment]
Since this issue was created, api_dump has received a json output. Karl mentioned using this to view the relevant bits of the dump. Now with the json format, a tool that post-processes api_dump to add in such state tracking info wouldn't be hard to create.  

The difficulty of adding state tracking to api_dump makes this an untenable feature to add, and unless someone has anything to add, this issue should be closed. A new issue to create a post processing script could be made if there is interest in such a tool.
