### ISSUE TITLE
Examples at https://github.com/SaschaWillems/Vulkan don't all trace and replay

### ISSUE THREAD

**Issue by Tony-LunarG** [LunarG/VulkanTools#49]
Specifically:

The instancing sample will trace, but nothing is drawn on replay

The raytracing sample gets this assert while tracing:
"vktrace_trace_packet_utils.c:147: vktrace_trace_packet_get_new_buffer_address: Assertion     `pHeader->size >= pHeader->next_buffers_offset + byteCount' failed".

The shadowmappingomni sample traces ok, replays ok, but segfaults when replayed with validation.  Running the sample with validation gets errors but no seg fault

I've seen all three of these on both Linux+Mesa and Windows+Nvidia

**Comment by jon-lunarg** [comment]
For the instancing example this is the well known tracing doesn't handle persistently mapped buffers issue.  Adding this code to the sample makes it work:
diff --git a/instancing/instancing.cpp b/instancing/instancing.cpp
index 4406dc9..a2d31bb 100644
--- a/instancing/instancing.cpp
+++ b/instancing/instancing.cpp
@@ -541,6 +541,12 @@ public:
                }
 
                memcpy(uniformData.vsScene.mapped, &uboVS, sizeof(uboVS));
+               VkMappedMemoryRange mr = {};
+               mr.memory = uniformData.vsScene.memory;
+               mr.offset = 0;
+               mr.size = sizeof(uboVS);
+
+               VK_CHECK_RESULT(vkFlushMappedMemoryRanges(device, 1, &mr));
        }

**Comment by jon-lunarg** [comment]
Argggh, Github doesn't like pasted in code diffs!  The bulleted list is the added lines to updateUniformBuffer()

**Comment by jon-lunarg** [comment]
The raytracing sample exposes bug in vkCreateComputePipelines trace layer where the size of the trace packet is not computed correctly.

**Comment by jon-lunarg** [comment]
The shadowmappingomni example seg faults during vkreplay when I use the loader installed with Nvidia driver that is pre-device layer deprecation with only VK_INSTANCE_LAYERS  defined. With a more recent loader using VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation completes  on replay.  Of course it gives some validation messages though.

Raytracing example has been fixed.  In my testing with Intel Mesa all samples that work with Mesa work with trace/replay except instancing that uses PMBs. Since their is a separate issue for vktrace PMB support, closing this issue.
