### ISSUE TITLE
Enhancement request - Make traces more OS independent

### ISSUE THREAD

**Issue by Tony-LunarG** [LunarG/VulkanTools#52]
It would be nice if vkreplay could know what OS it was running on and translate WSI calls from the trace to WSI calls appropriate for the system it was replaying on.

**Comment by vinjn** [comment]
There are two issues here:
1. Knowing which OS vkreplay is running, this information is provided at compilation stage.
2. Translating WSI calls, which is also trivial by having `WSI_replay_windows.cpp`, `WSI_replay_linux.cpp`, `WSI_replay_android.cpp` etc.
And each of these files will implement all the WSI calls, including those from other platforms.

**Comment by jon-lunarg** [comment]
Vinjn:

Do you have code that addresses these issues you could share?

**Comment by karl-lunarg** [comment]
I think this used to work.  Around May 19, I was able to create a trace of the cube app on Windows and play it back on Linux.

Now we get:

```
vkreplay error: Return value VK_ERROR_EXTENSION_NOT_PRESENT from API call (vkCreateInstance) does not match return value from trace file VK_SUCCESS.
vkreplay error: Failed to replay packet_id 7.

```

**Comment by vinjn** [comment]
@jon-lunarg nope, cross platform replay is still among my todo list.

**Comment by karl-lunarg** [comment]
I can't get it to work using code from back around the time when I got it working.  I think I must have made a quick hack to get things limping along in order to get something else done (Someone was debugging a problem with a Windows app and only had access to a Linux debug env).  So the hack never evolved into getting something that could be submitted.

LunarG is tracking this work item in our internal tracking system (issue VT-5), where I documented some of this.  IIRC, all I really had to do was fix up vkReplay::manually_replay_vkCreateInstance() to load the WSI extension appropriate for the replay platform.  Currently, it tries to load the one CreateInstance loaded while making the trace.  After fixing this, everything downstream seemed to work pretty well.  The WSI call translation mentioned above was already in place.

If there is an immediate need, I can try to make the changes again, or show someone else the details.

**Comment by karl-lunarg** [comment]
I found my partial work and passed it to Tony.

**Comment by Tony-LunarG** [comment]
I've fixed the extensions in CreateInstance, and David is going to take it from here.

**Comment by Tony-LunarG** [comment]
Note that memory types and properties have been changing from driver to driver, so a trace that blindly uses memory type 2 on playback could be getting memory with different properties than it got when the trace was recorded.  I think the replayer will need to map memory types with properties on record to memory types with the same properties on playback for all allocations.

**Comment by davidlunarg** [comment]
Implemented, closing. Note the memory types comment by Tony-LunarG on Jun 20 is not really part of this issue - memory types (and queue types) are a problem independent of OS, VulkanTools Issue #64 and VulkanTools #67 are for those two problems.
