### ISSUE TITLE
VK_LAYER_LUNARG_api_dump: Toggle dump behavior on/off based on some condition

### ISSUE THREAD

**Issue by vikramkushwaha** [LunarG/VulkanTools#603]
Would it be useful to toggle the dump on/off based on an environment variable or number of frames? I am running a large application and I am interested in the API calls after a 10 minute run. The initial ~8 GB of log is useless to me.
I think this could be a common use case.

**Comment by davidlunarg** [comment]
I agree, it would be a common use case to only want to see a certain range of frames.

Would tracing the application with trim enabled so that only frames within a certain range are captured, then playing back the trace with api_dump enabled meet your needs?

How about enabling api_dump and then running your app, sending the output to a script that will discard everything before the frame of interest?

I'm not proposing either of the above is the solution, but putting them forth in order to better understand what type of output you are looking for.

**Comment by vikramkushwaha** [comment]
Yes, api capture/replay should help in theory. 
I am not sure about sending output to a script. Could you add a little more info?

**Comment by davidlunarg** [comment]
Could you try a trimmed capture and replay to see if it works? If there are problems with trimming and/or replaying, I would be glad to work with you to address this.

As to how a script might work, the script would copy stdin to stdout, discarding all input up to and including the line containing the Nth occurrence of the text "vkQueuePresentKHR" and also discarding all lines after the Mth occurrence of the text 'vkQueuePresentKHR". This would result in the output containing all the api calls for frames N-M. Should be fairly easy to write in bash or python.

**Comment by vikramkushwaha** [comment]
Unfortunately the application (unreleased, not public yet) does not allow a capture. (It does not allow to be launched in Vulkan mode when tracing layer is enabled). 

I understand how the script would work, but what I was looking for how to pipe the stdout to a script on Windows.  I think I got it in Python:
output = Popen(["mycmd", "myarg"], stdout=PIPE).communicate()[0]

I can't promise I can try it today.

**Comment by vikramkushwaha** [comment]
For some reason I am unable to get output of the validation layers to stdout.  
file.exe > file works fine though.
I am using the 1.1.82.0 version and my env variable is set:
VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation

**Comment by karl-lunarg** [comment]
If your app is on Windows and it is NOT a console app, then the stdin and stdout handles are closed when your application starts, unless redirected to a file.  This [article](https://stackoverflow.com/questions/21646641/where-does-printf-writes-in-a-windows-non-console-application) and this [article](https://stackoverflow.com/questions/573724/how-can-i-redirect-stdout-to-some-visible-display-in-a-windows-application) discuss the details and some approaches to do what you want.   I suspect further web searches would turn up more. 

You're really hitting a generic restriction in Windows where windowed apps don't really have a stdin or stdout.  Most windowed apps are started from a launch icon or menu item and not from a textual command line, where there is no place for these streams to go.

You've already seen that redirecting the API dump output to a file probably doesn't solve your problem that well since you will end up writing the entire API dump to a file anyway, where you would then post-process it to get the parts you want.

The advantage of doing `MyApp | MyFilter`, where "MyFilter" is your script that discards everything you don't want, is that the large API dump file isn't saved anywhere and is passed a little at a time to your filter, which just writes the parts you want to a file.  Sadly, this doesn't seem that doable on Windows with non-console apps.  I don't know if `MyApp | MyFilter` (using a pipe to send MyApp stdout to your console app MyFilter's stdin) would work.

I've gone ahead and marked this issue as an enhancement request since the original request seems like a reasonable one.

**Comment by vikramkushwaha** [comment]
To make it more complex, my use case scenario is that the application is launched indirectly via another application. (a game run through steam)

**Comment by vikramkushwaha** [comment]
Perhaps an easier way to implement this would be on the lines of how the screenshot layers uses the VK_SCREENSHOT_FRAMES environment variable to only capture required frames. In this example, it would only dump the API calls for specified frames.

**Comment by charles-lunarg** [comment]
Created pull request #768 that implements this behavior, following the VK_SCREENSHOT_FRAMES style.
Can use environmental variables as well as the api_dump configuration options file.

**Comment by charles-lunarg** [comment]
PR is merged
