### ISSUE TITLE
api_dump: When "no address" mode is selected, output Handles with a UniqueID

### ISSUE THREAD

**Issue by MarkY-LunarG** [LunarG/VulkanTools#798]
When a user selects "no address" mode for API Dump, the handles are not listed.  Instead, it would be nice if API Dump assigned each new handle a unique ID so that different runs of the same program could be easily compared.

Ideally, this would mean that each handle type would have a ID in the upper 32-bits and an index in the lower 32-bits for the 64-bit handle.  That way, even if the calls to create different types of handles occurred in different orders (based on the behavior of a multithreaded app), the items could still be organized/viewed in a way that made sense to the person comparing the dumps.

**Comment by charles-lunarg** [comment]
Created PR #847 to address this.

**Comment by charles-lunarg** [comment]
Close PR, due to object handle aliasing. It might be possible that using Validation layers while running api_dump (and piggy backing the unique objects layer) wouldn't suffer from that issue, but as it stands re implementing the logic in vulkan isn't feasible.

**Comment by charles-lunarg** [comment]
Closing the issue due to unreasonable amount of effort to create. Recreating the unique object tracking in apidump poses a significant rewrite and would have to be updated whenever new handle types are added. And depending on the Validation Layers Unique Objects layer is a requirement that restricts how apidump can be used unnecessarily.
