### ISSUE TITLE
Add the ability to print timestamps to api_dump layer

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#800]
It would be useful to see where things slow down / hang

**Comment by charles-lunarg** [comment]
Added this functionality in PR #854 but is off by default, to preserve the current behavior. The timestamp is the time in microseconds since apidump started. 

While it wouldn't be hard to dump the duration of a vulkan call with apidump, I don't think it is a very appropriate place to do so. A proper profiler should be used instead, as it could better diagnose time spent inside the driver versus validation layers versus writing data out, which is most of what apidumps time is spent doing.
