### ISSUE TITLE
Replay of SaschaWillems samples are missing the text overlay

### ISSUE THREAD

**Issue by plohrmann** [LunarG/VulkanTools#81]
Most of Sascha Willems' Vulkan samples have a text overlay in the top left corner, however after trace & replay of these samples, the text overlay is missing during the replay. 

Oddly enough, when using RenderDoc to launch vkreplay with the same trace file as above, the text overlay is visible!

**Comment by davidlunarg** [comment]
This problem was introduced with the Sascha Willems' Samples commit 5e528cb9a36e7ced87fbdabceef73af8c130dfa4 -"Persitent mapped buffer for text overlay, fixed compiler warnings". If a trace is created from the Samples source prior to this commit, the replay  displays overlay text. If the trace is created from Samples source with this commit, the replay does not have overlay text. This is a persistently mapped memory issue with trace/replay, which is being worked on. I won't close this issue, as a reminder to try these samples with trace/replay after the mapped memory issues in trace/replay have been addressed.

**Comment by davidlunarg** [comment]
Closing, will track this problem in Issue #69
