### ISSUE TITLE
Enhancement ideas for VIA on Windows

### ISSUE THREAD

**Issue by mikew-lunarg** [LunarG/VulkanTools#829]
(found during Windows SDK 1.1.108 testing)
The "user experience" of VIA on Windows could be improved. 

What happens now:
1. a console window opens
1. vkcube windows will pop open and close
1. the console window closes.

Refinement/enhancement requests:
* Give some human-informative status messages in the console while vkcube is running.
* Keep the console window open, and report where the results file could be found.  Let the user close it.
* Open the .html file in a browser automatically.

These features could be implemented with a .bat script around the executable.

**Comment by mikew-lunarg** [comment]
From https://gitlab.khronos.org/vulkan/Vulkan-SDK-Packaging/issues/59

**Comment by mikew-lunarg** [comment]
Have notice that on different runs: 0, 1, or 2 vkcube windows will pop open and close.
Is the variable number of vkcube windows just a race condition, or indicating failures?
The vkcube runs (and possible error?) could be reported in the console.

**Comment by MarkY-LunarG** [comment]
The number of VkCube windows is based on whether or not VkCube is found.  This is reported in the console window as well as any success/failure messages.

- If it fails to find VkCube, no window appears, and a warning message is written into the generated HTML file.
- If it finds VkCube, it will at least run once, ideally twice.
  - First run just attempts to run VkCube to make sure it executes
  - Second run attempts to run with Validation layers enabled.
  - Again, a failure at any point will be output to the console as well as written to the generated HTML file.

This is all documented in the VIA readme that is also included with every SDK: https://github.com/LunarG/VulkanTools/blob/master/via/README.md#running.

So, per your requests:

1. Give some human-informative status messages in the console while vkcube is running.
  - This is done in several ways as mentioned above.
2. Keep the console window open, and report where the results file could be found. Let the user close it.
  - This was deemed by us early on as too intrusive.  The generated HTML file was believed to be sufficient.
3. Open the .html file in a browser automatically.
  - Since this can be run remotely, we didn't believe this was an option.  Perhaps we can revisit this.

**Comment by mikew-lunarg** [comment]
I think much of this can be addressed adding informative clues to a persistent command window:
- attempt and outcome of each vkcube run
- the location of the .html file.

Tested on my machine, the console is on-screen less than 7 seconds and much of that time under the vkcube windows.  Hard to tell if any useful info was there.

The observed variable number of vkcube windows were observed on successive start menu launches of a single SDK install.  The presence of vkcube should not be a factor in that?  Is there another failure mode?

**Comment by davidlunarg** [comment]
This issue is primarily addressed by pull request https://github.com/LunarG/VulkanTools/pull/1728. This pull request changed via so that it does not close the console window until the user has pressed enter in the console. A prior change to via opens the html file automatically and displays the location of the html file in the url.

Closing this issue.
