### ISSUE TITLE
Will the trace file be back compatible?

### ISSUE THREAD

**Issue by jyangsh** [LunarG/VulkanTools#91]
We are planning to use the vktrace replayer to run some regular tests with the captured game trace files. But we are worrying if we will need re-capture all the old trace files once the vktrace is updated.

So will the trace file be back compatible?

**Comment by ardaLunarG** [comment]
This is something we are trying to achieve, keeping a trace data base and replay them for test and performance comparison reasons. 

So backward compatibility is in our radar but case by case there are not covered cases (due to missing functionality in trace/replay or new features in vulkan or vulkan gpu drivers)
Ex: changing memory functionality cause lots of mismatches. 

Thus we keep a version number in trace files and print if replay supported version does not match to trace file. For now these cases we recommend go to older matching version of vkreplay.  

Saying that, as backward compatibility is something we want to provide please feel free to file bugs even though the issue is due to mismatching trace versions so we can keep track of problem cases and fix them if possible. If you can share the trace files that would help on reproducing the issue. You can upload traces to LunarXchange.

**Comment by jyangsh** [comment]
Got it, thank you very much! :)
