### ISSUE TITLE
Vulkan Configurator: apidump layer outputfile should use an extension consistent with output format

### ISSUE THREAD

**Issue by davidlunarg** [LunarG/VulkanTools#940]
If I specify an output format of html when enabling the api dump layer using vkconfig, the default log filename has an extension of .txt. Would be better if the default file name extension was changed to .html when the output format is changed.

**Comment by charles-lunarg** [comment]
As vkconfig is currently implemented, it would be very difficult to add this feature. This is due to vkconfig's layer settings information being a json file, not bespoke code. 

It would be be better to make the api_dump layer handle this directly. 
This poses a problem now, as api_dump needs to handle when the user might specify a output type and filename with an extension that doesn't match. 
It could report an error and crash, or report an warning but still use the provided filename (with no modification). 
It could change the extension to match, but this might overwrite an existing file silently if the file already existed.
Another, albeit obnoxious, solution is to simply tack on the extension, eg `dump_output.txt.json`.

**Comment by KarenGhavam-lunarG** [comment]
@richard-lunarg We should assess if this issue still applies with the new vkconfig

**Comment by richard-lunarg** [comment]
I 90% agree with Charles on this. This should be handled by the layer, and probably by sticking an .html or .json at the end if that's the file type. The user specifies the log filename. Much like in Photoshop, I can force save a .jpg but call it .png instead. The 10% hesitation is the Khronos layer has all kinds of special requirements and dependencies among the settings and we are in fact handling that "manually". Fixing this though in vkconfig seems more like a bandaid. 

We should leave the extension off completely and let the file type determine it. This can be done pretty easily (says the guy who doesn't have to do it) in that particular layer. If the user sticks .txt on the end anyway and it's not txt, then override it in the layer. Most software works this way for this kind of problem.

**Comment by charles-lunarg** [comment]
I also don't think this is a good case for 'special' handling like there is in the khronos validation layer. The khronos validation 'special' stuff is invariants defined by khronos, while api_dump its just a filename extension, a well known phenomenon, just like the photoshop example.

Looking over this, I actually prefer the 'obnoxious' solution. Make api_dump tack on the correct file extension unless it already exists. Reasoning is that altering a wrong extension is much more intrusive than just adding the right one, and most of the time the user should just not have the extension in the first place. This would obviously have to be documented, but I believe this follows the rule of least astonishment.
Example
"test.txt" -> "test.txt", "werid.json" -> "weird.json.html", "best" -> "best.json"

**Comment by christophe-lunarg** [comment]
This issue is fixed thanks to API dump settings presets.
